bot:
  prefix: "!"
  status: "for pokemon"

cogs:
  go_fest: false
  trainer_cards: true
  air_support: true
  events: true

logging:
  format: "%(asctime)s: %(levelname)-9s %(name)-16s :: %(message)s"
  date_format: "%m/%d/%Y %I:%M:%S %p"
  level: DEBUG
